### ISSUE TITLE
Link to "Raw logs" doesn't work anymore

### ISSUE THREAD

**Issue by famod** [quarkusio/quarkus-bot#165]
E.g. here: https://github.com/quarkusio/quarkus/pull/21590#issuecomment-976701702

![click](https://user-images.githubusercontent.com/22860528/143064850-da74d61a-bd16-498f-9381-55c42163f3ff.png)

brings me to the first job in the workflow (instead of the raw logs of the selected run):

![job](https://user-images.githubusercontent.com/22860528/143065049-8776d438-5813-4c65-8dc3-2eff8ce05461.png)

**Comment by gsmet** [comment]
Yeah they apparently changed the default URL of the workflow to include `?check_suite_focus=true` and what we did was too brittle. Working on a fix.

**Comment by gsmet** [comment]
Fix pushed to production.

**Comment by famod** [comment]
Fastest fix ever 😁 thanks!
