### ISSUE TITLE
Frequent "Errors occurred while downloading the build reports. This report is incomplete."

### ISSUE THREAD

**Issue by famod** [quarkusio/quarkus-bot#166]
E.g. https://github.com/quarkusio/quarkus/pull/21590#issuecomment-976701702

Maybe the reports have gotten to large and only failed reports should be included?

**Comment by gsmet** [comment]
From what I can see in the logs, the only errors I have are: `timeout while connecting to https://api.github.com/repos/quarkusio/quarkus/actions/artifacts/117797504/zip`.

I'll see if I can add more logs.

**Comment by gsmet** [comment]
I tried to improve the situation as much as I can. From what I can see the endpoint to download artifacts is often unavailable.
