### ISSUE TITLE
Use linked issues API to get linked issues

### ISSUE THREAD

**Issue by gsmet** [quarkusio/quarkus-bot#194]
At the moment, we are extracting the fixed issues from the description of the PR because there was no way in the API to get the list of issues connected to a pull request.

GitHub apparently added this feature to their GraphQL API in December:
https://github.community/t/get-all-issues-linked-to-a-pull-request/14653/14

```graphql
{
  resource(url: "https://github.com/Org/Repo/pull/1234") {
    ... on PullRequest {
      closingIssuesReferences(first: 10) {
        nodes {
          number
        }
      }
    }
  }
}
```
I don't see it added to the REST API but we should check if they are included somehow in the PR payload (my guess is that it is not).

I also think we should keep the current `IssueExtractor` and merge the results of both methods.

Note that it's now very easy to inject a GraphQL client. See https://github.com/quarkusio/quarkus-github-bot/blob/main/src/main/java/io/quarkus/bot/TriageDiscussion.java#L40 for an example.

**Comment by gsmet** [comment]
@gastaldi FYI

**Comment by johurul000** [comment]
Hi, @gsmet I am a beginner and I would like to work on this. 
And it would be very helpful if you could explain a little more.
