### ISSUE TITLE
include reason for mention/cc

### ISSUE THREAD

**Issue by maxandersen** [quarkusio/quarkus-bot#297]
in my constant battle on tuning my ever growing notification inflow I was wondering if this change to quarkus bot would be useful to others:

Instead of just seeing 

`/cc @gsmet, @manovotn, @maxandersen, @radcortez, @Sanne` 

on a PR/issue like https://github.com/quarkusio/quarkus/pull/29537 I was thinking to do this:

`/cc @gsmet(deps), @manovotn(smallrye), @maxandersen(deps), @radcortez(smallrye), @Sanne(deps)` 

Letting me know at a faster glance reason why I'm being pinged.
 
Implementation idea is simply to add optional id to the matchers in `quarkus-bot.yaml` and whatever id gets matched first add that as reason to a mention.

Could also add all reasons but feels like it could get quite long for some ?

If interesting I can have a stab at it.

**Comment by gsmet** [comment]
Fixed in https://github.com/quarkusio/quarkus-github-bot/pull/299 .

**Comment by maxandersen** [comment]
is it live now?

**Comment by maxandersen** [comment]
ah i see it now - its live. awesomeness.

**Comment by gsmet** [comment]
Yeah, I pushed it yesterday.
