### ISSUE TITLE
Complain loudly when someone adds a triage/backport* label to an issue

### ISSUE THREAD

**Issue by gsmet** [quarkusio/quarkus-bot#303]
It happened a few times lately that one of the `triage/backport*` labels was added to an issue instead of the corresponding pull request, which led to pull requests being ignored when backporting.

When a backport label is added to an issue (and not a PR), we should:
- add a comment to the issue saying this is not something that should be done
- the comment should explicitly ping the user who added the backport label

**Comment by gsmet** [comment]
@NicolasGras I thought you might be interested by this one?

**Comment by nicolasgras** [comment]
@gsmet you can assign it to me, I'm gonna work on it.

**Comment by gsmet** [comment]
Cool, thanks!
