### ISSUE TITLE
Mentioning a team should mention individual users instead

### ISSUE THREAD

**Issue by gsmet** [quarkusio/quarkus-bot#317]
It's still not working to mention a team with a bot: it used to not work at all, now apparently, the mention is a real mention but @gastaldi told me he still doesn't receive the notifications.

So first we need to check if the bot can have the permission to read the team members.

Once we have checked that, we can pursue with:
- when mentioning someone, check if it's a team, if it's a team, get the members and instead of mentioning the team, we would mention the members individually. Obviously, the members needs to be added back into the set and the team removed so that we don't have duplicates
- a team is a mention containing a `/` (maybe it's not entirely true but I think we can live with this simplification)
- we should probably cache the team members for one hour or so: the cache extension is already around so it should be easy

@NicolasGras if you're looking for another fun issue: here you are :)

**Comment by gsmet** [comment]
Let's wait a bit on this one. I adjusted the permissions for the bot and maybe it will solve our problem.

**Comment by gsmet** [comment]
Actually, changing the permission fixed the issue.

**Comment by nicolasgras** [comment]
Ok, I'll wait to have another fun issue :)
