### ISSUE TITLE
Determine why an issue ended up tagged with bearer-token

### ISSUE THREAD

**Issue by gsmet** [quarkusio/quarkus-bot#342]
There is something very odd here: https://github.com/quarkusio/quarkus/issues/33602 .

Let's try to go to the bottom of this.

**Comment by michalvavrik** [comment]
When triage label was removed, all users that weren't already participating and are connected to rule with label `security` were collected. `area/security` label is assigned to `jwt`, `security` and `bearer-token`. All `notify` users were `sberyozkin` and `pedroigor`, so only `pedroigor` was notified.

It is exactly how it was described here https://github.com/quarkusio/quarkus-github-bot/issues/43#issuecomment-802573964 and here https://github.com/quarkusio/quarkus-github-bot/pull/44 and it goes down to https://github.com/quarkusio/quarkus-github-bot/blob/d2580e13ee96e1bce118076edf8e2621e69b10e0/src/main/java/io/quarkus/bot/PingWhenNeedsTriageRemoved.java#L73

I suggest to use `quarkus-github-lottery` participants. They have assigned labels they maintain, therefore is source of truth. However these maintainers differ from `quarkus-github-bot.yml` and there is less of them. Maybe choose maintainers from `quarkus-github-lottery` and keep `quarkus-github-bot` as fallback when noone was matched?

I can do it when I find a time.

**Comment by gsmet** [comment]
Ah right, I missed we were in this case. Thanks for taking the time to have a look!
